### ISSUE TITLE
make it optionally non-blocking (vibe.d aware)

### ISSUE THREAD

**Issue by MartinNowak** [Burgos/postgres-native#1]
See [Writing native database drivers - and a new MySQL driver port - vibe.d](http://vibed.org/blog/posts/writing-native-db-drivers) on how to use a sightly different socket/Connection when `version (Have_vibe_d_core)` is defined.
Eventually someone should abstract that socket difference away in some dub library.
Actually replacing std.socket while being at it would make sense as well ;). Unfortunately the io lib looks rather abandoned, [Add socket streams. by tmccombs · Pull Request #3 · jasonwhite/io](https://github.com/jasonwhite/io/pull/3).

**Comment by Burgos** [comment]
Thanks for the suggestion, I will implement it here, should be trivial, since reading from socket is done at a single place in the codebase.

Great idea about dub library, I will see if I get some time to play with it before summer.

**Comment by Burgos** [comment]
Example main optionally using vibe.d system:

https://github.com/Burgos/postgres-native/blob/master/src/app.d#L49-L65
